name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'scripts/install.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'scripts/install.sh'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip di')"
    environment: lidar

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub          
      uses: docker/login-action@v2          
      with:            
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0
      with:
        platforms: arm64
    
    - name: Build and Push arm64
      uses: docker/build-push-action@v3.1.0
      with:
        file: ./Dockerfile
        push: true
        platforms: linux/arm64
        tags: hpdlidar/lidar:latest
        
    - name: Build and Push arm32
      uses: docker/build-push-action@v3.1.0
      with:
        file: ./Dockerfile
        push: true
        platforms: linux/arm32v7
        tags: hpdlidar/lidar:latest32
