name: Setup Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'setup.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'setup.sh'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip st')"
    
    steps:
    - name: Setup
      shell: bash
      run: |
        find .
        chmod +x "${GITHUB_WORKSPACE}/setup.sh"
        "${GITHUB_WORKSPACE}/setup.sh"
